extends Node
## Web3 autoload. Drop this in your project's `addons/web3/` folder and add it
## to Project Settings → Autoload as "Web3".
##
## All methods return Godot-compatible values (dicts, strings, ints, arrays).
## Network calls are made via JavaScriptBridge.eval() which round-trips to
## the browser-side @browser-forge/web3-sdk.
##
## This autoload is generated by BrowserForge's export pipeline — the runtime
## SDK is automatically injected into every exported game's index.html.

signal wallet_connected(chain: String, address: String)
signal wallet_disconnected(chain: String)
signal accounts_changed(address: String)
signal chain_changed(chain: String)
signal transaction_signed(signature: String, payload: String)

const SOLANA := "solana"
const BASE := "base"
const POLYGON := "polygon"

var _bridge: Object = null
var _config: Dictionary = {}


func _ready() -> void:
	# JavaScriptBridge is only available when running on the web platform
	if ClassDB.class_exists("JavaScriptBridge"):
		_bridge = ClassDB.instantiate("JavaScriptBridge")
		# Pull the per-project config injected by the build
		var raw := JavaScriptBridge.eval("JSON.stringify(window.__BF_WEB3_CONFIG__ || {})", true)
		if raw != null and raw != "":
			var parsed = JSON.parse_string(raw)
			if parsed is Dictionary:
				_config = parsed
	# Hook the EVM event listeners via the SDK
	if _bridge != null:
		JavaScriptBridge.eval("""
			if (window.Web3 && window.Web3.on) {
			  window.__bfEvtAcc = window.Web3.on('accountsChanged', (a) => {
			    document.dispatchEvent(new CustomEvent('bf:accountsChanged', { detail: a }));
			  });
			  window.__bfEvtChain = window.Web3.on('chainChanged', (c) => {
			    document.dispatchEvent(new CustomEvent('bf:chainChanged', { detail: c }));
			  });
			}
		""", true)


# ------------------------------------------------------------
# Public API
# ------------------------------------------------------------

func is_web3_enabled() -> bool:
	return _config.get("enabled", false)


func supported_chains() -> Array:
	return _config.get("chains", [])


func has_wallet(chain: String) -> bool:
	if _bridge == null:
		return false
	var raw := JavaScriptBridge.eval("window.Web3 && window.Web3.hasWallet && window.Web3.hasWallet('%s')" % chain, true)
	return raw == "true"


## Connect a wallet. Returns { chain, address } or { error: "..." }.
func connect(chain: String) -> Dictionary:
	if _bridge == null:
		return { "error": "Not running in a web build" }
	var js := """
		new Promise((resolve) => {
		  window.Web3.connect('%s')
		    .then((c) => resolve(JSON.stringify({ ok: true, chain: c.chain, address: c.address })))
		    .catch((e) => resolve(JSON.stringify({ ok: false, error: e.message || String(e) })));
		})
	""" % chain
	var raw = JavaScriptBridge.eval(js, true)
	var parsed = JSON.parse_string(raw)
	if typeof parsed != TYPE_DICTIONARY:
		return { "error": "No response from wallet" }
	if parsed.get("ok", false):
		var res := { "chain": parsed["chain"], "address": parsed["address"] }
		wallet_connected.emit(parsed["chain"], parsed["address"])
		return res
	return { "error": parsed.get("error", "Unknown error") }


func disconnect(chain: String) -> void:
	if _bridge == null:
		return
	JavaScriptBridge.eval("window.Web3 && window.Web3.disconnect && window.Web3.disconnect('%s')" % chain, true)
	wallet_disconnected.emit(chain)


func get_address(chain: String) -> String:
	if _bridge == null:
		return ""
	var raw := JavaScriptBridge.eval("window.Web3 && window.Web3.getAddress ? window.Web3.getAddress('%s') : ''" % chain, true)
	if raw == null:
		return ""
	# Eval returns the value as a JSON-encoded string for non-primitives
	return _unwrap_string(raw)


## Returns { amount, decimals, symbol, mint }
func get_balance(chain: String, opts: Dictionary = {}) -> Dictionary:
	if _bridge == null:
		return { "error": "Not running in a web build" }
	var js := """
		new Promise((resolve) => {
		  var o = %s;
		  window.Web3.getBalance('%s', o)
		    .then((b) => resolve(JSON.stringify({ ok: true, amount: b.amount, decimals: b.decimals, symbol: b.symbol || '', mint: b.mint })))
		    .catch((e) => resolve(JSON.stringify({ ok: false, error: e.message || String(e) })));
		})
	""" % [JSON.stringify(opts), chain]
	var raw = JavaScriptBridge.eval(js, true)
	var parsed = JSON.parse_string(raw)
	if typeof parsed != TYPE_DICTIONARY:
		return { "error": "Invalid balance response" }
	if parsed.get("ok", false):
		return {
			"amount": parsed["amount"],
			"decimals": parsed["decimals"],
			"symbol": parsed.get("symbol", ""),
			"mint": parsed.get("mint", ""),
		}
	return { "error": parsed.get("error", "Balance check failed") }


## Sign an arbitrary message (e.g. for auth, leaderboard, NFT mint auth).
func sign_message(chain: String, message: String) -> Dictionary:
	if _bridge == null:
		return { "error": "Not running in a web build" }
	var js := """
		new Promise((resolve) => {
		  window.Web3.signMessage('%s', %s)
		    .then((r) => resolve(JSON.stringify({ ok: true, signature: r.signature, payload: r.payload })))
		    .catch((e) => resolve(JSON.stringify({ ok: false, error: e.message || String(e) })));
		})
	""" % [chain, JSON.stringify(message)]
	var raw = JavaScriptBridge.eval(js, true)
	var parsed = JSON.parse_string(raw)
	if typeof parsed != TYPE_DICTIONARY:
		return { "error": "Invalid sign response" }
	if parsed.get("ok", false):
		transaction_signed.emit(parsed["signature"], parsed["payload"])
		return { "signature": parsed["signature"], "payload": parsed["payload"] }
	return { "error": parsed.get("error", "Sign failed") }


# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

func _unwrap_string(raw) -> String:
	# JavaScriptBridge.eval returns a Variant; primitive strings come back
	# as the raw value, quoted strings come back as JSON-encoded strings.
	if raw is String:
		# If it looks like a JSON string literal, unquote it
		if raw.length() >= 2 and raw[0] == '"' and raw[raw.length() - 1] == '"':
			return raw.substr(1, raw.length() - 2)
		return raw
	return str(raw)
